apiVersion: builtin
kind: PatchTransformer
metadata:
  name: set-oauth2
target:
  group: networking.k8s.io
  version: v1beta1
  kind: Ingress
  name: ingress
patch: |-
  apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    name: ingress
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: https://auth.$(DOMAIN)/oauth2/start?rd=%2F$server_name$escaped_request_uri
      nginx.ingress.kubernetes.io/auth-url: https://auth.$(DOMAIN)/oauth2/auth
