apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/dsyer/docker-services/layers/samples/petclinic
- ../ingress
patchesStrategicMerge:
- service.yaml
vars:
  - name: HOST
    objref:
      apiVersion: v1
      kind: Service
      name: app
  - name: DOMAIN
    objref:
      apiVersion: v1
      kind: Service
      name: app
    fieldref:
      fieldpath: metadata.annotations.domain
