apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: demo-
commonLabels:
  app: demo
commonAnnotations:
  domain: sub.dsyer.com
resources:
- github.com/dsyer/docker-services/layers/base
- ingress.yaml
transformers:
- github.com/dsyer/docker-services/layers/env
- github.com/dsyer/docker-services/layers/prometheus
- github.com/dsyer/docker-services/layers/actuator
images:
  - name: dsyer/template
    newName: dsyer/demo
vars:
  - name: HOST
    objref:
      apiVersion: v1
      kind: Service
      name: app
  - name: DOMAIN
    objref:
      apiVersion: v1
      kind: Service
      name: app
    fieldref:
      fieldpath: metadata.annotations.domain
configurations:
  - varreference.yaml