apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: demo-
commonLabels:
  app: demo
resources:
- github.com/dsyer/docker-services/layers/base
- ../ingress
patchesStrategicMerge:
- service.yaml
transformers:
- github.com/dsyer/docker-services/layers/env
- github.com/dsyer/docker-services/layers/prometheus
- github.com/dsyer/docker-services/layers/actuator
- ../oauth2
images:
  - name: dsyer/template
    newName: dsyer/demo
vars:
  - name: HOST
    objref:
      apiVersion: v1
      kind: Service
      name: app
  - name: DOMAIN
    objref:
      apiVersion: v1
      kind: Service
      name: app
    fieldref:
      fieldpath: metadata.annotations.domain
